// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Sidebar pour "The App"
  theAppSidebar: [
    {
      type: "doc",
      id: "the-app/intro",
      label: "Getting Started",
    },
    {
      type: "doc",
      id: "the-app/install",
      label: "Installation",
    },
    {
      type: "doc",
      id: "the-app/tests",
      label: "Tests available",
    },
  ],

  // Sidebar pour "Technical Doc"
  technicalSidebar: [
    {
      type: "category",
      label: "Frontend",
      items: [{ type: "autogenerated", dirName: "frontend" }],
    },
    {
      type: "category",
      label: "Backend",
      items: [{ type: "autogenerated", dirName: "backend" }],
    },
  ],
};

export default sidebars;
